// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PreAnalyse.proto

package byone.hbase.protobuf;

public final class PreAnalyseProtos {
  private PreAnalyseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MapEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string key = 1;
    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // required string value = 2;
    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code MapEntry}
   */
  public static final class MapEntry extends
      com.google.protobuf.GeneratedMessage
      implements MapEntryOrBuilder {
    // Use MapEntry.newBuilder() to construct.
    private MapEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MapEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MapEntry defaultInstance;
    public static MapEntry getDefaultInstance() {
      return defaultInstance;
    }

    public MapEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MapEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return byone.hbase.protobuf.PreAnalyseProtos.internal_static_MapEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return byone.hbase.protobuf.PreAnalyseProtos.internal_static_MapEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              byone.hbase.protobuf.PreAnalyseProtos.MapEntry.class, byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<MapEntry> PARSER =
        new com.google.protobuf.AbstractParser<MapEntry>() {
      public MapEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapEntry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MapEntry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof byone.hbase.protobuf.PreAnalyseProtos.MapEntry)) {
        return super.equals(obj);
      }
      byone.hbase.protobuf.PreAnalyseProtos.MapEntry other = (byone.hbase.protobuf.PreAnalyseProtos.MapEntry) obj;

      boolean result = true;
      result = result && (hasKey() == other.hasKey());
      if (hasKey()) {
        result = result && getKey()
            .equals(other.getKey());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.MapEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(byone.hbase.protobuf.PreAnalyseProtos.MapEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MapEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return byone.hbase.protobuf.PreAnalyseProtos.internal_static_MapEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return byone.hbase.protobuf.PreAnalyseProtos.internal_static_MapEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                byone.hbase.protobuf.PreAnalyseProtos.MapEntry.class, byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder.class);
      }

      // Construct using byone.hbase.protobuf.PreAnalyseProtos.MapEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return byone.hbase.protobuf.PreAnalyseProtos.internal_static_MapEntry_descriptor;
      }

      public byone.hbase.protobuf.PreAnalyseProtos.MapEntry getDefaultInstanceForType() {
        return byone.hbase.protobuf.PreAnalyseProtos.MapEntry.getDefaultInstance();
      }

      public byone.hbase.protobuf.PreAnalyseProtos.MapEntry build() {
        byone.hbase.protobuf.PreAnalyseProtos.MapEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public byone.hbase.protobuf.PreAnalyseProtos.MapEntry buildPartial() {
        byone.hbase.protobuf.PreAnalyseProtos.MapEntry result = new byone.hbase.protobuf.PreAnalyseProtos.MapEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof byone.hbase.protobuf.PreAnalyseProtos.MapEntry) {
          return mergeFrom((byone.hbase.protobuf.PreAnalyseProtos.MapEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(byone.hbase.protobuf.PreAnalyseProtos.MapEntry other) {
        if (other == byone.hbase.protobuf.PreAnalyseProtos.MapEntry.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        byone.hbase.protobuf.PreAnalyseProtos.MapEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (byone.hbase.protobuf.PreAnalyseProtos.MapEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // required string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MapEntry)
    }

    static {
      defaultInstance = new MapEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MapEntry)
  }

  public interface AnalyseRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string filterString = 1;
    /**
     * <code>optional string filterString = 1;</code>
     */
    boolean hasFilterString();
    /**
     * <code>optional string filterString = 1;</code>
     */
    java.lang.String getFilterString();
    /**
     * <code>optional string filterString = 1;</code>
     */
    com.google.protobuf.ByteString
        getFilterStringBytes();

    // repeated bytes events = 2;
    /**
     * <code>repeated bytes events = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getEventsList();
    /**
     * <code>repeated bytes events = 2;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated bytes events = 2;</code>
     */
    com.google.protobuf.ByteString getEvents(int index);

    // repeated string groups = 3;
    /**
     * <code>repeated string groups = 3;</code>
     */
    java.util.List<java.lang.String>
    getGroupsList();
    /**
     * <code>repeated string groups = 3;</code>
     */
    int getGroupsCount();
    /**
     * <code>repeated string groups = 3;</code>
     */
    java.lang.String getGroups(int index);
    /**
     * <code>repeated string groups = 3;</code>
     */
    com.google.protobuf.ByteString
        getGroupsBytes(int index);
  }
  /**
   * Protobuf type {@code AnalyseRequest}
   */
  public static final class AnalyseRequest extends
      com.google.protobuf.GeneratedMessage
      implements AnalyseRequestOrBuilder {
    // Use AnalyseRequest.newBuilder() to construct.
    private AnalyseRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AnalyseRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AnalyseRequest defaultInstance;
    public static AnalyseRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AnalyseRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AnalyseRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              filterString_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                events_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              events_.add(input.readBytes());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                groups_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              groups_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          groups_ = new com.google.protobuf.UnmodifiableLazyStringList(groups_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest.class, byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AnalyseRequest> PARSER =
        new com.google.protobuf.AbstractParser<AnalyseRequest>() {
      public AnalyseRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnalyseRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AnalyseRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string filterString = 1;
    public static final int FILTERSTRING_FIELD_NUMBER = 1;
    private java.lang.Object filterString_;
    /**
     * <code>optional string filterString = 1;</code>
     */
    public boolean hasFilterString() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string filterString = 1;</code>
     */
    public java.lang.String getFilterString() {
      java.lang.Object ref = filterString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filterString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string filterString = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilterStringBytes() {
      java.lang.Object ref = filterString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filterString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated bytes events = 2;
    public static final int EVENTS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> events_;
    /**
     * <code>repeated bytes events = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getEventsList() {
      return events_;
    }
    /**
     * <code>repeated bytes events = 2;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated bytes events = 2;</code>
     */
    public com.google.protobuf.ByteString getEvents(int index) {
      return events_.get(index);
    }

    // repeated string groups = 3;
    public static final int GROUPS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList groups_;
    /**
     * <code>repeated string groups = 3;</code>
     */
    public java.util.List<java.lang.String>
        getGroupsList() {
      return groups_;
    }
    /**
     * <code>repeated string groups = 3;</code>
     */
    public int getGroupsCount() {
      return groups_.size();
    }
    /**
     * <code>repeated string groups = 3;</code>
     */
    public java.lang.String getGroups(int index) {
      return groups_.get(index);
    }
    /**
     * <code>repeated string groups = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGroupsBytes(int index) {
      return groups_.getByteString(index);
    }

    private void initFields() {
      filterString_ = "";
      events_ = java.util.Collections.emptyList();
      groups_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilterStringBytes());
      }
      for (int i = 0; i < events_.size(); i++) {
        output.writeBytes(2, events_.get(i));
      }
      for (int i = 0; i < groups_.size(); i++) {
        output.writeBytes(3, groups_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilterStringBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < events_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(events_.get(i));
        }
        size += dataSize;
        size += 1 * getEventsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < groups_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(groups_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getGroupsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest)) {
        return super.equals(obj);
      }
      byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest other = (byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest) obj;

      boolean result = true;
      result = result && (hasFilterString() == other.hasFilterString());
      if (hasFilterString()) {
        result = result && getFilterString()
            .equals(other.getFilterString());
      }
      result = result && getEventsList()
          .equals(other.getEventsList());
      result = result && getGroupsList()
          .equals(other.getGroupsList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFilterString()) {
        hash = (37 * hash) + FILTERSTRING_FIELD_NUMBER;
        hash = (53 * hash) + getFilterString().hashCode();
      }
      if (getEventsCount() > 0) {
        hash = (37 * hash) + EVENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEventsList().hashCode();
      }
      if (getGroupsCount() > 0) {
        hash = (37 * hash) + GROUPS_FIELD_NUMBER;
        hash = (53 * hash) + getGroupsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnalyseRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest.class, byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest.Builder.class);
      }

      // Construct using byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        filterString_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        groups_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseRequest_descriptor;
      }

      public byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest getDefaultInstanceForType() {
        return byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest.getDefaultInstance();
      }

      public byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest build() {
        byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest buildPartial() {
        byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest result = new byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filterString_ = filterString_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          events_ = java.util.Collections.unmodifiableList(events_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.events_ = events_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          groups_ = new com.google.protobuf.UnmodifiableLazyStringList(
              groups_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.groups_ = groups_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest) {
          return mergeFrom((byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest other) {
        if (other == byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest.getDefaultInstance()) return this;
        if (other.hasFilterString()) {
          bitField0_ |= 0x00000001;
          filterString_ = other.filterString_;
          onChanged();
        }
        if (!other.events_.isEmpty()) {
          if (events_.isEmpty()) {
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEventsIsMutable();
            events_.addAll(other.events_);
          }
          onChanged();
        }
        if (!other.groups_.isEmpty()) {
          if (groups_.isEmpty()) {
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureGroupsIsMutable();
            groups_.addAll(other.groups_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string filterString = 1;
      private java.lang.Object filterString_ = "";
      /**
       * <code>optional string filterString = 1;</code>
       */
      public boolean hasFilterString() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string filterString = 1;</code>
       */
      public java.lang.String getFilterString() {
        java.lang.Object ref = filterString_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          filterString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string filterString = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilterStringBytes() {
        java.lang.Object ref = filterString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filterString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filterString = 1;</code>
       */
      public Builder setFilterString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filterString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filterString = 1;</code>
       */
      public Builder clearFilterString() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filterString_ = getDefaultInstance().getFilterString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string filterString = 1;</code>
       */
      public Builder setFilterStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filterString_ = value;
        onChanged();
        return this;
      }

      // repeated bytes events = 2;
      private java.util.List<com.google.protobuf.ByteString> events_ = java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          events_ = new java.util.ArrayList<com.google.protobuf.ByteString>(events_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes events = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEventsList() {
        return java.util.Collections.unmodifiableList(events_);
      }
      /**
       * <code>repeated bytes events = 2;</code>
       */
      public int getEventsCount() {
        return events_.size();
      }
      /**
       * <code>repeated bytes events = 2;</code>
       */
      public com.google.protobuf.ByteString getEvents(int index) {
        return events_.get(index);
      }
      /**
       * <code>repeated bytes events = 2;</code>
       */
      public Builder setEvents(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEventsIsMutable();
        events_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes events = 2;</code>
       */
      public Builder addEvents(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEventsIsMutable();
        events_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes events = 2;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEventsIsMutable();
        super.addAll(values, events_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes events = 2;</code>
       */
      public Builder clearEvents() {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // repeated string groups = 3;
      private com.google.protobuf.LazyStringList groups_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGroupsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          groups_ = new com.google.protobuf.LazyStringArrayList(groups_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string groups = 3;</code>
       */
      public java.util.List<java.lang.String>
          getGroupsList() {
        return java.util.Collections.unmodifiableList(groups_);
      }
      /**
       * <code>repeated string groups = 3;</code>
       */
      public int getGroupsCount() {
        return groups_.size();
      }
      /**
       * <code>repeated string groups = 3;</code>
       */
      public java.lang.String getGroups(int index) {
        return groups_.get(index);
      }
      /**
       * <code>repeated string groups = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGroupsBytes(int index) {
        return groups_.getByteString(index);
      }
      /**
       * <code>repeated string groups = 3;</code>
       */
      public Builder setGroups(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupsIsMutable();
        groups_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groups = 3;</code>
       */
      public Builder addGroups(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupsIsMutable();
        groups_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groups = 3;</code>
       */
      public Builder addAllGroups(
          java.lang.Iterable<java.lang.String> values) {
        ensureGroupsIsMutable();
        super.addAll(values, groups_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groups = 3;</code>
       */
      public Builder clearGroups() {
        groups_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groups = 3;</code>
       */
      public Builder addGroupsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupsIsMutable();
        groups_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AnalyseRequest)
    }

    static {
      defaultInstance = new AnalyseRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AnalyseRequest)
  }

  public interface AnalyseResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .MapEntry items = 1;
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    java.util.List<byone.hbase.protobuf.PreAnalyseProtos.MapEntry> 
        getItemsList();
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    byone.hbase.protobuf.PreAnalyseProtos.MapEntry getItems(int index);
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    java.util.List<? extends byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AnalyseResponse}
   */
  public static final class AnalyseResponse extends
      com.google.protobuf.GeneratedMessage
      implements AnalyseResponseOrBuilder {
    // Use AnalyseResponse.newBuilder() to construct.
    private AnalyseResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AnalyseResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AnalyseResponse defaultInstance;
    public static AnalyseResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AnalyseResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AnalyseResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<byone.hbase.protobuf.PreAnalyseProtos.MapEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(byone.hbase.protobuf.PreAnalyseProtos.MapEntry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.class, byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AnalyseResponse> PARSER =
        new com.google.protobuf.AbstractParser<AnalyseResponse>() {
      public AnalyseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnalyseResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AnalyseResponse> getParserForType() {
      return PARSER;
    }

    // repeated .MapEntry items = 1;
    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<byone.hbase.protobuf.PreAnalyseProtos.MapEntry> items_;
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    public java.util.List<byone.hbase.protobuf.PreAnalyseProtos.MapEntry> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    public java.util.List<? extends byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    public byone.hbase.protobuf.PreAnalyseProtos.MapEntry getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .MapEntry items = 1;</code>
     */
    public byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse)) {
        return super.equals(obj);
      }
      byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse other = (byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse) obj;

      boolean result = true;
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnalyseResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.class, byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.Builder.class);
      }

      // Construct using byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return byone.hbase.protobuf.PreAnalyseProtos.internal_static_AnalyseResponse_descriptor;
      }

      public byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse getDefaultInstanceForType() {
        return byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.getDefaultInstance();
      }

      public byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse build() {
        byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse buildPartial() {
        byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse result = new byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse) {
          return mergeFrom((byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse other) {
        if (other == byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .MapEntry items = 1;
      private java.util.List<byone.hbase.protobuf.PreAnalyseProtos.MapEntry> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<byone.hbase.protobuf.PreAnalyseProtos.MapEntry>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          byone.hbase.protobuf.PreAnalyseProtos.MapEntry, byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder, byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public java.util.List<byone.hbase.protobuf.PreAnalyseProtos.MapEntry> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public byone.hbase.protobuf.PreAnalyseProtos.MapEntry getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public Builder setItems(
          int index, byone.hbase.protobuf.PreAnalyseProtos.MapEntry value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public Builder setItems(
          int index, byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public Builder addItems(byone.hbase.protobuf.PreAnalyseProtos.MapEntry value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public Builder addItems(
          int index, byone.hbase.protobuf.PreAnalyseProtos.MapEntry value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public Builder addItems(
          byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public Builder addItems(
          int index, byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends byone.hbase.protobuf.PreAnalyseProtos.MapEntry> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          super.addAll(values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public java.util.List<? extends byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            byone.hbase.protobuf.PreAnalyseProtos.MapEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, byone.hbase.protobuf.PreAnalyseProtos.MapEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .MapEntry items = 1;</code>
       */
      public java.util.List<byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          byone.hbase.protobuf.PreAnalyseProtos.MapEntry, byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder, byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              byone.hbase.protobuf.PreAnalyseProtos.MapEntry, byone.hbase.protobuf.PreAnalyseProtos.MapEntry.Builder, byone.hbase.protobuf.PreAnalyseProtos.MapEntryOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:AnalyseResponse)
    }

    static {
      defaultInstance = new AnalyseResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AnalyseResponse)
  }

  /**
   * Protobuf service {@code PreAnalyseService}
   */
  public static abstract class PreAnalyseService
      implements com.google.protobuf.Service {
    protected PreAnalyseService() {}

    public interface Interface {
      /**
       * <code>rpc getPreData(.AnalyseRequest) returns (.AnalyseResponse);</code>
       */
      public abstract void getPreData(
          com.google.protobuf.RpcController controller,
          byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest request,
          com.google.protobuf.RpcCallback<byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new PreAnalyseService() {
        @java.lang.Override
        public  void getPreData(
            com.google.protobuf.RpcController controller,
            byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest request,
            com.google.protobuf.RpcCallback<byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse> done) {
          impl.getPreData(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getPreData(controller, (byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getPreData(.AnalyseRequest) returns (.AnalyseResponse);</code>
     */
    public abstract void getPreData(
        com.google.protobuf.RpcController controller,
        byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest request,
        com.google.protobuf.RpcCallback<byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return byone.hbase.protobuf.PreAnalyseProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getPreData(controller, (byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest)request,
            com.google.protobuf.RpcUtil.<byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends byone.hbase.protobuf.PreAnalyseProtos.PreAnalyseService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getPreData(
          com.google.protobuf.RpcController controller,
          byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest request,
          com.google.protobuf.RpcCallback<byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.class,
            byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse getPreData(
          com.google.protobuf.RpcController controller,
          byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse getPreData(
          com.google.protobuf.RpcController controller,
          byone.hbase.protobuf.PreAnalyseProtos.AnalyseRequest request)
          throws com.google.protobuf.ServiceException {
        return (byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          byone.hbase.protobuf.PreAnalyseProtos.AnalyseResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:PreAnalyseService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MapEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MapEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AnalyseRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AnalyseRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AnalyseResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AnalyseResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PreAnalyse.proto\"&\n\010MapEntry\022\013\n\003key\030\001 " +
      "\002(\t\022\r\n\005value\030\002 \002(\t\"F\n\016AnalyseRequest\022\024\n\014" +
      "filterString\030\001 \001(\t\022\016\n\006events\030\002 \003(\014\022\016\n\006gr" +
      "oups\030\003 \003(\t\"+\n\017AnalyseResponse\022\030\n\005items\030\001" +
      " \003(\0132\t.MapEntry2D\n\021PreAnalyseService\022/\n\n" +
      "getPreData\022\017.AnalyseRequest\032\020.AnalyseRes" +
      "ponseB0\n\024byone.hbase.protobufB\020PreAnalys" +
      "eProtosH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MapEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MapEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MapEntry_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_AnalyseRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_AnalyseRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AnalyseRequest_descriptor,
              new java.lang.String[] { "FilterString", "Events", "Groups", });
          internal_static_AnalyseResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_AnalyseResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AnalyseResponse_descriptor,
              new java.lang.String[] { "Items", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
